version: "2"

volumes:
    pgdatavol:
        driver: local
        
services:
    pgdata:
        image: pobsteta/docker-base
        container_name: pgdata        
        volumes:
          - pgdatavol:/var/lib/postgresql/data
        
    db:        
        image: pobsteta/bef-db
        container_name: db
        volumes_from:
        - pgdata
        ports:        
        - "35432:5432"
        environment:
        - POSTGRES_USER=docker
        - POSTGRES_PASSWORD=docker
        restart: always

    sime:        
        image: pobsteta/bef-sime
        container_name: sime
        depends_on:
        - db        
        volumes_from:
        - pgdata             
        ports:
        - "8000:8000"
        - "8001:8001"        
        links:
        - db
        restart: always
        

